table Calendar
	lineageTag: 4c561c60-fc72-4395-a864-f1b2dc720c88

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 410229d0-caf8-4f81-b96e-a53ed41554fc
		summarizeBy: none
		sourceColumn: Date

		variation Variación
			isDefault
			relationship: 05dd31e9-934c-4d4e-8a5b-90aa5613ca66
			defaultHierarchy: LocalDateTable_13400e41-3b31-4f44-a624-090436c02019.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 252dfcbe-6b53-40c0-a572-0566a51d8c7c
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column TrimNum
		dataType: int64
		formatString: 0
		lineageTag: c5b966d4-0d1d-4a0d-8cd0-62d9f165a359
		summarizeBy: sum
		sourceColumn: TrimNum

		annotation SummarizationSetBy = Automatic

	column TrimNom
		dataType: string
		lineageTag: eb64cefe-9182-46ad-9d1d-a2c971d2e078
		summarizeBy: none
		sourceColumn: TrimNom

		annotation SummarizationSetBy = Automatic

	column MesNum
		dataType: int64
		formatString: 0
		lineageTag: e82a99ad-4d78-41e3-a6b8-19c94aa1c6d1
		summarizeBy: sum
		sourceColumn: MesNum

		annotation SummarizationSetBy = Automatic

	column MesNom
		dataType: string
		lineageTag: 00b610ed-7202-4b13-b956-ebf29996bcfc
		summarizeBy: none
		sourceColumn: MesNom

		annotation SummarizationSetBy = Automatic

	column MesNomAB
		dataType: string
		lineageTag: f67b9fa2-4e18-4a96-a42e-960718d76982
		summarizeBy: none
		sourceColumn: MesNomAB

		annotation SummarizationSetBy = Automatic

	column SemNrmNum
		dataType: int64
		formatString: 0
		lineageTag: 4acd15f5-ae7a-4696-969f-9b9d828f7cd7
		summarizeBy: sum
		sourceColumn: SemNrmNum

		annotation SummarizationSetBy = Automatic

	column DiaNum
		dataType: int64
		formatString: 0
		lineageTag: f2fffd1b-ac1b-41e2-8635-50d9bd6c41e5
		summarizeBy: sum
		sourceColumn: DiaNum

		annotation SummarizationSetBy = Automatic

	column DiaNom
		dataType: string
		lineageTag: 5a2b7bfd-be02-4ba2-8e4a-bfed6d20e8f9
		summarizeBy: none
		sourceColumn: DiaNom

		annotation SummarizationSetBy = Automatic

	column DiaNomAB
		dataType: string
		lineageTag: da9f2700-5b9c-4b82-9a47-2ffc693352ee
		summarizeBy: none
		sourceColumn: DiaNomAB

		annotation SummarizationSetBy = Automatic

	column MesCalendario
		dataType: int64
		formatString: 0
		lineageTag: 9cd575e3-eab1-4006-891c-6ddec21b4eba
		summarizeBy: sum
		sourceColumn: MesCalendario

		annotation SummarizationSetBy = Automatic

	column DiaSemNum
		dataType: string
		lineageTag: 7c231fdd-af07-4020-9df4-31d9f3af85ee
		summarizeBy: none
		sourceColumn: DiaSemNum

		annotation SummarizationSetBy = Automatic

	column MesAño
		dataType: string
		lineageTag: 31462167-a817-4504-9c82-c134b1ee0d8c
		summarizeBy: none
		sourceColumn: MesAño

		annotation SummarizationSetBy = Automatic

	column FiltroActual
		dataType: string
		lineageTag: ce1dda50-3321-4aea-a089-2f544883e6d5
		summarizeBy: none
		sourceColumn: FiltroActual

		annotation SummarizationSetBy = Automatic

	column FiltroActual_MA
		dataType: string
		lineageTag: 196e4f2e-10f3-4583-923b-ef04636f0b6b
		summarizeBy: none
		sourceColumn: FiltroActual_MA

		annotation SummarizationSetBy = Automatic

	partition Calendar = m
		mode: import
		queryGroup: Calendar
		source = ```
				let
				    Origen = #"StartDate",
				    #"Convertida en tabla" = #table(1, {{Origen}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Convertida en tabla",{{"Column1", "StartDate"}}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas con nombre cambiado", "EndDate", each Date.From(DateTime.LocalNow ())),
				    #"Personalizada agregada1" = Table.AddColumn(#"Personalizada agregada", "Dates", each {Number.From([StartDate])..Number.From([EndDate])}),
				    Dates = #"Personalizada agregada1"{0}[Dates],
				    #"Convertida en tabla1" = Table.FromList(Dates, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Renamed Columns" = Table.RenameColumns(#"Convertida en tabla1",{{"Column1", "DateKey"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"DateKey", type date}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Año", each Date.Year([DateKey])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Año", Int64.Type}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "TrimNum", each Date.QuarterOfYear([DateKey])),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"TrimNum", Int64.Type}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "TrimNom", each "Trim " & Number.ToText(Date.QuarterOfYear([DateKey]))),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "MesNum", each Date.Month([DateKey])),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom3", "MesNom", each Text.Proper(Date.MonthName([DateKey],"es-ES"))),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"MesNum", Int64.Type}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type3", "MesNomAB", each Text.Start(Text.Proper(Date.MonthName([DateKey],"es-ES")),3)),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom5",{{"MesNomAB", type text}}),
				    #"Added Custom6" = Table.AddColumn(#"Changed Type4", "SemNrmNum", each Date.WeekOfYear([DateKey],1)),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom6",{{"SemNrmNum", Int64.Type}}),
				    #"Added Custom8" = Table.AddColumn(#"Changed Type5", "DiaNum", each Date.Day([DateKey])),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom8",{{"DiaNum", Int64.Type}}),
				    #"Added Custom9" = Table.AddColumn(#"Changed Type7", "DiaNom", each Text.Proper(Date.DayOfWeekName([DateKey], "eS-ES"))),
				    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "DiaNomAB", each Text.Start(Text.Proper(Date.DayOfWeekName([DateKey], "eS-ES")),3)),
				    #"Added Custom11" = Table.AddColumn(#"Added Custom10", "AñoMes", each Number.ToText([Año])&"-"& [MesNomAB]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom11",{{"AñoMes", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type8",{"AñoMes"}),
				    #"Added Custom12" = Table.AddColumn(#"Removed Columns", "MesP", each Date.ToText([DateKey], "MMM", "es-419")),
				    #"Removed Columns1" = Table.RemoveColumns(#"Added Custom12",{"MesP"}),
				    #"Added Custom13" = Table.AddColumn(#"Removed Columns1", "Custom", each Number.ToText([Año])&Text.PadStart(Number.ToText([MesNum]),2,"0")),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Custom13",{{"Custom", "MesCalendario"}}),
				    #"Added Custom14" = Table.AddColumn(#"Renamed Columns1", "DiaSemNum", each Date.DayOfWeek([DateKey],Day.Monday)),
				    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "Custom", each Number.ToText([Año])&"-"&[MesNomAB]),
				    #"Texto en mayúsculas" = Table.TransformColumns(#"Added Custom15",{{"Custom", Text.Upper, type text}}),
				    #"Renamed Columns2" = Table.RenameColumns(#"Texto en mayúsculas",{{"Custom", "YM"}, {"DateKey", "Date"}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Renamed Columns2", "fecha_curso", each DateTimeZone.UtcNow ()),
				    #"Mes insertado" = Table.AddColumn(#"Personalizada agregada2", "mes_curso", each Date.Month([fecha_curso]), Int64.Type),
				    #"Año insertado" = Table.AddColumn(#"Mes insertado", "año_curso", each Date.Year([fecha_curso]), Int64.Type),
				    #"Personalizada agregada3" = Table.AddColumn(#"Año insertado", "año_mes_curso", each Number.ToText([año_curso])&Text.PadStart(Number.ToText([mes_curso]),2,"0")),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Personalizada agregada3",{{"año_mes_curso", Int64.Type}, {"MesCalendario", Int64.Type}}),
				    #"Columna condicional agregada" = Table.AddColumn(#"Tipo cambiado", "filtro_general", each 
				if [MesCalendario] = [año_mes_curso] then "Mes en curso" else
				if [MesCalendario] = [año_mes_curso]-1 then "Mes anterior" else
				if [MesCalendario] = [año_mes_curso]-2 then "Hace 2 Meses" else
				if [MesCalendario] = [año_mes_curso]-3 then "Hace 3 Meses" else
				if [MesCalendario] = [año_mes_curso]-4 then "Hace 4 Meses" else
				if [MesCalendario] = [año_mes_curso]-5 then "Hace 5 Meses" else
				if [MesCalendario] = [año_mes_curso]-6 then "Hace 6 Meses" else "Mayor a 6 Meses"),
				    #"Personalizada agregada4" = Table.AddColumn(#"Columna condicional agregada", "Mes Año", each if Date.Month([Date]) = Date.Month(DateTime.LocalNow()) and Date.Year([Date]) = Date.Year(DateTime.LocalNow()) then "Mes En Curso" else [YM]),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Personalizada agregada4",{"fecha_curso", "mes_curso", "año_curso", "año_mes_curso"}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Columnas quitadas",{{"Mes Año", "FiltroActual_MA"}, {"filtro_general", "FiltroActual"}, {"YM", "MesAño"}})
				in
				    #"Columnas con nombre cambiado1"
				```

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

